'use client';
import {renderText} from '@/modules/shared/utils/renderText';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import AdminShell from '@/modules/admin/components/AdminShell';
import MetricCard from '@/modules/shared/components/MetricCard';
import {useAdmin} from '@/modules/admin/components/AdminStore';

const entitlementDefaults=['Core course library','Company reporting','Custom learning paths','Company Academy','Onboarding programs','Credential registry','SSO / provisioning','API access'];

export default function AdminCompanyDetail({id}){
  const {data,updateItem,addItem,removeItem,log}=useAdmin();
  const c=data.companies.find(x=>x.id===id);
  const [tab,setTab]=useState('overview');
  const [note,setNote]=useState('');
  const notes=useMemo(()=>data.accountNotes?.filter(n=>n.companyId===id)||[],[data.accountNotes,id]);
  const tickets=useMemo(()=>data.support?.filter(t=>t.customer===c?.name)||[],[data.support,c?.name]);
  if(!c)return <AdminShell active="companies" title="Company account" description="Company not found."/>;
  const seatUse=Math.round((c.used/Math.max(c.seats,1))*100);
  function p(patch,action='Updated company account'){updateItem('companies',id,patch);log(action,c.name)}
  function addNote(){if(!note.trim())return;addItem('accountNotes',{companyId:id,author:'Stefan Admin',body:note.trim(),created:'Now',type:'Customer success'});log('Added account note',c.name);setNote('')}
  function lifecycleAction(status){p({status},`${status} company account`)}
  const riskClass=c.renewalRisk==='Low'?'success':c.renewalRisk==='High'?'danger':'warning';
  return <AdminShell active="companies" eyebrow="Owner Admin / Company Account" title={c.name} description="Operate the customer relationship, subscription, entitlements, learning adoption, support and renewal lifecycle from one account workspace." actions={<><span className={`status ${c.status==='Active'?'success':'warning'}`}>{c.status}</span><button className="button button-small" onClick={()=>lifecycleAction(c.status==='Active'?'Paused':'Active')}>{c.status==='Active'?'Pause account':'Activate account'}</button></>}>
    <div className="builder-topbar"><Link className="text-link" href="/admin/companies">← All companies</Link><div className="row"><span className="muted small">Owner: {c.owner||'Unassigned'}</span><span className={`status ${riskClass}`}>{c.renewalRisk||'Low'} renewal risk</span></div></div>
    <div className="admin-tabs">{[['overview','Overview'],['success','Customer Success'],['subscription','Subscription'],['learning','Learning'],['academy','Company Academy'],['support','Support'],['settings','Account Settings']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{renderText(l)}</button>)}</div>

    {tab==='overview'&&<>
      <div className="dashboard-cards"><MetricCard value={`${c.used}/${c.seats}`} label="Seat utilization"/><MetricCard value={`${seatUse}%`} label="Seats in use"/><MetricCard value={`${c.health||0}/100`} label="Account health"/><MetricCard value={c.renewal} label="Renewal"/></div>
      <div className="grid-2"><div className="dashboard-panel"><h3>Account profile</h3>{[['Plan',c.plan],['Lifecycle',c.lifecycle||c.status],['Primary admin',c.admin],['Customer owner',c.owner||'Unassigned'],['Last contact',c.lastContact||'—'],['Next review',c.nextReview||'—']].map(([a,b])=><div className="admin-pipeline-row" key={a}><span>{renderText(a)}</span><b>{renderText(b)}</b></div>)}</div><div className="dashboard-panel"><h3>Customer health</h3><div className="health-row"><span className={`health-dot ${(c.adoption||0)>=75?'good':'warning'}`}/><div><b>{c.adoption||0}% learning adoption</b><p className="muted small">Active use of assigned learning across licensed seats.</p></div></div><div className="health-row"><span className={`health-dot ${(c.openTickets||0)>1?'warning':'good'}`}/><div><b>{c.openTickets||0} open support cases</b><p className="muted small">Review unresolved cases before the next success meeting.</p></div></div><div className="health-row"><span className={`health-dot ${riskClass==='success'?'good':'warning'}`}/><div><b>{c.renewalRisk||'Low'} renewal risk</b><p className="muted small">Demo health signal based on adoption, support and commercial activity.</p></div></div></div></div>
      <div className="dashboard-panel"><div className="row-between"><div><h3>Recommended account actions</h3><p className="muted small">Customer-success actions generated from the current account state.</p></div><span className="pill">Health {c.health||0}/100</span></div><div className="settings-check-grid"><div><b>Prepare next review</b><p className="muted small">Review learning adoption and unresolved support topics before {c.nextReview||'the next meeting'}.</p><button className="ghost-button" onClick={()=>{p({nextReview:'Sep 15, 2026'},'Scheduled customer review')}}>Schedule review</button></div><div><b>Check seat expansion</b><p className="muted small">{Math.max(c.seats-c.used,0)} seats remain. Consider an expansion conversation above 85% utilization.</p><button className="ghost-button" onClick={()=>setTab('subscription')}>Review subscription</button></div><div><b>Learning intervention</b><p className="muted small">Use role-specific assignments when team completion is below target.</p><button className="ghost-button" onClick={()=>setTab('learning')}>Review learning</button></div></div></div>
    </>}

    {tab==='success'&&<div className="grid-2"><div className="dashboard-panel"><div className="row-between"><div><h3>Customer-success plan</h3><p className="muted small">Keep commercial context and success actions attached to the account.</p></div><span className={`status ${riskClass}`}>{c.renewalRisk||'Low'} risk</span></div><div className="cms-form-grid"><label className="field"><span>Lifecycle stage</span><select value={c.lifecycle||'Customer'} onChange={e=>p({lifecycle:e.target.value})}><option>Pilot</option><option>Onboarding</option><option>Customer</option><option>Expansion</option><option>Renewal</option><option>At risk</option></select></label><label className="field"><span>Customer owner</span><input value={c.owner||''} onChange={e=>p({owner:e.target.value})}/></label><label className="field"><span>Account health</span><input type="number" min="0" max="100" value={c.health||0} onChange={e=>p({health:Number(e.target.value)})}/></label><label className="field"><span>Learning adoption %</span><input type="number" min="0" max="100" value={c.adoption||0} onChange={e=>p({adoption:Number(e.target.value)})}/></label><label className="field"><span>Renewal risk</span><select value={c.renewalRisk||'Low'} onChange={e=>p({renewalRisk:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select></label><label className="field"><span>Next business review</span><input value={c.nextReview||''} onChange={e=>p({nextReview:e.target.value})}/></label></div></div><div className="dashboard-panel"><h3>Account notes</h3><textarea className="app-textarea" rows="4" placeholder="Add customer-success, commercial or implementation context…" value={note} onChange={e=>setNote(e.target.value)}/><button className="button button-small" onClick={addNote}>Add note</button><div className="stack compact" style={{marginTop:18}}>{notes.map(n=><div className="activity-row" key={n.id}><span className="activity-dot"/><div><b>{n.type}</b><p className="muted small">{n.body}</p><small className="muted">{n.author} · {n.created}</small></div><button className="ghost-button danger" onClick={()=>removeItem('accountNotes',n.id)}>×</button></div>)}{!notes.length&&<p className="muted small">No account notes yet.</p>}</div></div></div>}

    {tab==='subscription'&&<div className="grid-2"><div className="dashboard-panel"><h3>Subscription & renewal</h3><label className="field"><span>Plan</span><select value={c.plan} onChange={e=>p({plan:e.target.value})}><option>Pilot</option><option>Team</option><option>Business</option><option>Scale</option><option>Enterprise</option></select></label><label className="field"><span>Seats</span><input type="number" value={c.seats} onChange={e=>p({seats:Number(e.target.value)})}/></label><label className="field"><span>MRR equivalent (€)</span><input type="number" value={c.mrr} onChange={e=>p({mrr:Number(e.target.value)})}/></label><label className="field"><span>Renewal</span><input value={c.renewal} onChange={e=>p({renewal:e.target.value})}/></label><div className="row"><button className="button button-small" onClick={()=>{p({renewalRisk:'Low',lifecycle:'Renewal'},'Prepared renewal')}}>Prepare renewal</button><Link className="button button-secondary button-small" href="/admin/revenue">Revenue view</Link></div></div><div className="dashboard-panel"><h3>Account entitlements</h3><p className="muted small">These switches model customer-specific overrides on top of plan entitlements.</p><div className="setting-switches">{entitlementDefaults.map((x,i)=><label key={renderText(x)}><input type="checkbox" defaultChecked={i<3||c.plan!=='Team'}/> {renderText(x)}</label>)}</div></div></div>}

    {tab==='learning'&&<><div className="grid-2"><div className="dashboard-panel"><h3>Learning utilization</h3>{[['Foundation pathway',84],['Product pathway',71],['Operations pathway',78],['Leadership pathway',46]].map(([n,v])=><div className="analytics-progress" key={n}><div className="row-between"><span>{renderText(n)}</span><b>{renderText(v)}%</b></div><div className="progress"><span style={{width:`${v}%`}}/></div></div>)}</div><div className="dashboard-panel"><h3>Learning operations</h3><div className="admin-action-stack"><button className="button button-secondary" onClick={()=>log('Assigned required foundation',c.name)}>Assign required foundation</button><button className="button button-secondary" onClick={()=>log('Exported learning report',c.name)}>Export learning report</button><button className="button button-secondary" onClick={()=>log('Reset assessment attempt',c.name)}>Reset learner assessment</button><button className="button button-secondary" onClick={()=>log('Issued manual credential',c.name)}>Issue manual credential</button></div></div></div><div className="dashboard-panel"><div className="row-between"><h3>Learning health signals</h3><Link href="/admin/analytics" className="text-link small">Platform benchmark →</Link></div><div className="admin-summary-strip"><div><b>{c.adoption||0}%</b><span>Adoption</span></div><div><b>74%</b><span>Completion</span></div><div><b>86%</b><span>Assessment pass</span></div><div><b>11</b><span>Overdue items</span></div></div></div></>}

    {tab==='academy'&&<div className="grid-2"><div className="dashboard-panel"><h3>Private Company Academy</h3><div className="setting-switches"><label><input type="checkbox" defaultChecked/> Enable private content</label><label><input type="checkbox" defaultChecked/> Company-branded landing page</label><label><input type="checkbox" defaultChecked/> Internal assessments</label><label><input type="checkbox"/> Custom domain</label><label><input type="checkbox" defaultChecked={c.plan==='Scale'||c.plan==='Enterprise'}/> SSO access</label></div><label className="field"><span>Academy display name</span><input defaultValue={`${c.name} Academy`}/></label><div className="row"><Link href="/admin/company-academies" className="button button-small">Manage company content</Link><button className="button button-secondary button-small" onClick={()=>log('Opened Academy preview',c.name)}>Preview Academy</button></div></div><div className="dashboard-panel"><h3>Private learning statistics</h3><div className="metric-strip vertical"><div><b>8</b><span>Private modules</span></div><div><b>6</b><span>Published</span></div><div><b>82%</b><span>Completion</span></div><div><b>3</b><span>Internal assessments</span></div></div></div></div>}

    {tab==='support'&&<div className="grid-2"><div className="dashboard-panel"><div className="row-between"><div><h3>Support cases</h3><p className="muted small">Cases attached to this organization.</p></div><Link className="text-link small" href="/admin/support">Support operations →</Link></div>{tickets.map(t=><div className="assignment-row" key={t.id}><div><b>{t.subject}</b><p className="muted small">{t.id} · {t.owner} · {t.updated}</p></div><div><span className={`status ${t.priority==='High'?'danger':t.status==='Open'?'warning':''}`}>{t.status}</span></div></div>)}{!tickets.length&&<p className="muted">No open support cases attached to this account.</p>}</div><div className="dashboard-panel"><h3>Support controls</h3><div className="admin-action-stack"><button className="button button-secondary" onClick={()=>{addItem('support',{subject:'Account review requested',customer:c.name,priority:'Normal',status:'Open',owner:'Support Admin',updated:'Now'});p({openTickets:(c.openTickets||0)+1},'Created support case')}}>Create support case</button><button className="button button-secondary" onClick={()=>log('Started support impersonation session',c.name)}>Open support view</button><button className="button button-secondary" onClick={()=>log('Exported account activity',c.name)}>Export account activity</button></div><p className="muted small" style={{marginTop:16}}>Production impersonation should be time-limited, permission-gated and fully audited.</p></div></div>}

    {tab==='settings'&&<div className="grid-2"><div className="dashboard-panel"><h3>Account settings</h3><label className="field"><span>Company name</span><input value={c.name} onChange={e=>p({name:e.target.value})}/></label><label className="field"><span>Primary admin email</span><input value={c.admin} onChange={e=>p({admin:e.target.value})}/></label><label className="field"><span>Status</span><select value={c.status} onChange={e=>p({status:e.target.value})}><option>Pilot</option><option>Active</option><option>Paused</option><option>Cancelled</option></select></label><label className="field"><span>Last customer contact</span><input value={c.lastContact||''} onChange={e=>p({lastContact:e.target.value})}/></label></div><div className="dashboard-panel danger-panel"><div><h3>Account lifecycle</h3><p className="muted">Pausing blocks new learning activity while preserving history. Cancellation should require a retention/export decision in production.</p></div><div className="row"><button className="ghost-button" onClick={()=>lifecycleAction('Paused')}>Pause</button><button className="ghost-button danger" onClick={()=>{if(confirm('Cancel this company account?'))lifecycleAction('Cancelled')}}>Cancel account</button></div></div></div>}
  </AdminShell>
}
