'use client';
import {renderText} from '@/modules/shared/utils/renderText';
import {useState} from 'react';
import Link from 'next/link';
import {useLearning} from '@/modules/learner/components/LearningStore';

export default function AssessmentClient({course,questions}){
  const {setAssessment,setCourseProgress}=useLearning();
  const [index,setIndex]=useState(0); const [answers,setAnswers]=useState({}); const [finished,setFinished]=useState(false);
  const q=questions[index];
  const score=questions.reduce((sum,item,i)=>sum+(answers[i]===item.correct?1:0),0);
  const pct=Math.round(score/questions.length*100); const passed=pct>=80;
  async function finish(){setFinished(true);const program=course.title.replace(' Fundamentals','')+' Credential';let credentialId; if(pct>=80){try{const r=await fetch('/api/certificates/issue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Demo Learner',program,score:pct})});const d=await r.json();credentialId=d.credential?.credential_id}catch(e){}} setAssessment(course.slug,pct,program,credentialId);if(pct>=80)setCourseProgress(course.slug,100,course.modules?.length||course.lessons||1)}
  if(finished) return <div className="assessment-result card"><span className={passed?'score-ring passed':'score-ring'}>{pct}%</span><div><div className="eyebrow">Assessment complete</div><h2>{passed?'Passed — credential eligible':'Review and retry'}</h2><p className="lead">You answered {score} of {questions.length} questions correctly. The passing score for OpsAcademy professional assessments is 80%.</p><div className="hero-actions">{passed?<Link className="button" href="/dashboard/certificates">View certificate →</Link>:<button className="button" onClick={()=>{setFinished(false);setIndex(0);setAnswers({})}}>Retry assessment</button>}<Link className="button button-secondary" href={`/learn/${course.slug}`}>Return to course</Link></div></div></div>;
  return <div className="assessment-shell"><div className="assessment-top"><div><div className="eyebrow">Final assessment</div><h2>{course.title}</h2></div><span className="pill">Question {index+1} / {questions.length}</span></div><div className="progress" style={{marginBottom:28}}><span style={{width:`${((index+1)/questions.length)*100}%`}}></span></div><div className="card assessment-question"><h3>{q.question}</h3><div className="assessment-options">{q.options.map((option,i)=><button key={option} className={answers[index]===i?'option-button selected':'option-button'} onClick={()=>setAnswers({...answers,[index]:i})}><span>{String.fromCharCode(65+i)}</span>{renderText(option)}</button>)}</div>{answers[index]!==undefined&&<div className={answers[index]===q.correct?'feedback success':'feedback'}>{answers[index]===q.correct?'Correct. ':'Review this point. '}{q.explanation}</div>}</div><div className="row-between assessment-actions"><button className="button button-secondary" disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button>{index<questions.length-1?<button className="button" disabled={answers[index]===undefined} onClick={()=>setIndex(index+1)}>Next →</button>:<button className="button" disabled={answers[index]===undefined} onClick={finish}>Finish assessment</button>}</div></div>;
}
