'use client';
import {useEffect,useState} from 'react';
const seed=[{id:1,title:'Operator vs supplier',course:'Operations Foundations',body:'Operator owns the customer-facing service; suppliers provide infrastructure/content/services.',updated:'Today'},{id:2,title:'Launch readiness',course:'Product Fundamentals',body:'Remember QA, compliance review, support readiness, monitoring and rollback ownership.',updated:'Yesterday'}];
export default function LearnerNotes(){
  const [notes,setNotes]=useState(seed);const [title,setTitle]=useState('');const [body,setBody]=useState('');
  useEffect(()=>{let active=true;try{const s=localStorage.getItem('opsacademy-notes-v5');if(s)setNotes(JSON.parse(s))}catch(e){}fetch('/api/learner/notes',{cache:'no-store'}).then(r=>r.json()).then(j=>{if(active&&!j.demo&&Array.isArray(j.data))setNotes(j.data.map(n=>({id:n.id,title:n.title,course:'Personal note',body:n.body,updated:new Date(n.updated_at).toLocaleDateString()})))}).catch(()=>{});return()=>{active=false}},[]);
  useEffect(()=>{try{localStorage.setItem('opsacademy-notes-v5',JSON.stringify(notes))}catch(e){}},[notes]);
  async function add(){if(!title.trim()&&!body.trim())return;const local={id:Date.now(),title:title||'Untitled note',course:'Personal note',body,updated:'Now'};setNotes([local,...notes]);setTitle('');setBody('');try{const r=await fetch('/api/learner/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:local.title,body:local.body})});const j=await r.json();if(j.data?.id)setNotes(current=>current.map(n=>n.id===local.id?{...n,id:j.data.id}:n));}catch(e){}}
  function remove(id){setNotes(current=>current.filter(x=>x.id!==id));fetch(`/api/learner/notes?id=${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});}
  return <><div className="dashboard-panel"><h3>New note</h3><div className="field"><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What do you want to remember?"/></div><div className="field"><label>Note</label><textarea className="app-textarea" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a note from your course or own research..."/></div><button className="button button-small" onClick={add}>Save note</button></div><div className="grid-2">{notes.map(n=><div className="dashboard-panel note-card" key={n.id}><div className="row-between"><span className="pill">{n.course}</span><button className="ghost-button danger" onClick={()=>remove(n.id)}>Delete</button></div><h3 style={{marginTop:18}}>{n.title}</h3><p className="muted">{n.body}</p><span className="small muted">Updated {n.updated}</span></div>)}</div></>;
}
