'use client';
import {useState} from 'react';
const questions=[
 {q:'Which work do you enjoy most?',options:[['Turning needs into product requirements','Product'],['Coordinating incidents and daily service','Operations'],['Managing timelines and dependencies','Project Management'],['Leading people and performance','Leadership']]},
 {q:'Which capability do you want to strengthen?',options:[['Integrations and product ownership','Product'],['Escalation and operational governance','Operations'],['Risk and stakeholder management','Project Management'],['Delegation and cross-functional leadership','Leadership']]},
 {q:'Which output feels most familiar?',options:[['Feature brief','Product'],['Incident report','Operations'],['Project plan','Project Management'],['Team scorecard','Leadership']]}
];
const map={Product:'Product Professional',Operations:'Operations Professional','Project Management':'operations Project Manager',Leadership:'Team Lead'};
export default function SkillsAssessment(){const [answers,setAnswers]=useState([]);const [i,setI]=useState(0);function pick(type){const next=[...answers,type];setAnswers(next);setI(i+1)}if(i>=questions.length){const score=answers.reduce((o,x)=>(o[x]=(o[x]||0)+1,o),{});const best=Object.entries(score).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Product';return <div className="verify-card"><div className="eyebrow">Recommended development path</div><h2>{map[best]}</h2><p className="lead">Your answers align most closely with {best}. Use this as a starting point rather than a formal aptitude assessment.</p><a className="button" href="/learning-paths">View learning paths →</a></div>}const q=questions[i];return <div className="verify-card"><div className="row-between"><div className="eyebrow">Skills assessment</div><span className="pill">{i+1}/{questions.length}</span></div><h2>{q.q}</h2><div className="assessment-options">{q.options.map(([label,type])=><button className="option-button" key={label} onClick={()=>pick(type)}><span>→</span>{label}</button>)}</div></div>}
