import Link from 'next/link';
export const metadata = { title: 'Certifications — OpsAcademy' };
const certs = [
  ['OpsAcademy Industry Foundation','Core understanding of the operations ecosystem, terminology, departments and regulated business context.'],
  ['OpsAcademy Product Foundation','Foundation knowledge for product ownership, requirements, integrations, releases and cross-functional delivery.'],
  ['OpsAcademy Operations Professional','Operational ownership, incident handling, escalation, reporting and cross-team workflows.'],
  ['OpsAcademy Project Management','Applying project management to launches, integrations, dependencies and regulated operations environments.'],
  ['OpsAcademy Payments Foundation','Payment flows, PSP relationships, reconciliation concepts, failures, disputes and risk escalation.'],
  ['OpsAcademy Leadership','Team structure, governance, performance systems, reporting and cross-functional leadership.']
];
export default function CertificationsPage(){return <><section className="page-hero"><div className="container"><div className="eyebrow">Professional Certificates</div><h1>Demonstrate structured industry knowledge.</h1><p className="lead">Complete learning programs, pass assessments and receive a verifiable OpsAcademy credential with a unique certificate ID.</p><div className="hero-actions"><Link className="button" href="/certifications/verify">Verify credential →</Link><Link className="button button-secondary" href="/learning-paths">Explore learning paths</Link></div></div></section><section className="section"><div className="container grid-2">{certs.map(([title,desc])=><div className="card" key={title}><span className="pill">Verified credential</span><h3 style={{marginTop:22}}>{title}</h3><p className="muted">{desc}</p><div className="course-meta"><span>80% passing score</span><span>Credential ID</span><span>Verification page</span></div></div>)}</div></section><section className="section section-border"><div className="container band"><div className="section-head" style={{marginBottom:0}}><div className="eyebrow">Credibility first</div><h2>Clear about what the certificate means.</h2><p className="lead">OpsAcademy certificates validate completion of our professional learning programs. They should not be presented as regulator-issued licences, legal qualifications or governmental accreditation unless such accreditation is separately obtained.</p></div></div></section></>}
