'use client';
import AdminShell from '@/modules/admin/components/AdminShell';
import AdminTable from '@/modules/admin/components/AdminTable';
import AdminModal from '@/modules/admin/components/AdminModal';
import {useAdmin} from '@/modules/admin/components/AdminStore';
import {useState} from 'react';

export default function Page(){
 const {data,addItem,updateItem,removeItem,log}=useAdmin();const [modal,setModal]=useState(false);const [form,setForm]=useState({name:'New Learner',email:'',company:'Individual',plan:'Free',courses:0,certificates:0,lastActive:'Never',status:'Invited'});
 const bulk=(ids,status,clear)=>{ids.forEach(id=>updateItem('learners',id,{status}));log(`Bulk ${status.toLowerCase()} learners`,`${ids.length} accounts`);clear()};
 function create(){if(!form.name||!form.email)return;addItem('learners',form);log('Created learner',form.email);setModal(false)}
 return <AdminShell active="learners" eyebrow="Owner Admin / Customers" title="Learners" description="Operate individual and company learner accounts, access, status and support workflows in bulk." actions={<button className="button button-small" onClick={()=>setModal(true)}>Create learner +</button>}>
  <div className="admin-summary-strip"><div><b>{data.learners.length}</b><span>Accounts</span></div><div><b>{data.learners.filter(x=>x.status==='Active').length}</b><span>Active</span></div><div><b>{data.learners.filter(x=>x.company!=='Individual').length}</b><span>Company learners</span></div><div><b>{data.learners.reduce((s,x)=>s+(x.certificates||0),0)}</b><span>Credentials</span></div></div>
  <AdminTable viewKey="learners" rows={data.learners} searchKeys={['name','email','company','plan']} filters={['Active','Suspended','Invited','Free','Professional','Company']} bulkActions={[{label:'Activate',onClick:(ids,clear)=>bulk(ids,'Active',clear)},{label:'Suspend',danger:true,onClick:(ids,clear)=>bulk(ids,'Suspended',clear)}]} columns={[{key:'name',label:'Learner',render:r=><div><b>{r.name}</b><p className="muted small">{r.email}</p></div>},{key:'company',label:'Company'},{key:'plan',label:'Access'},{key:'courses',label:'Courses'},{key:'certificates',label:'Credentials'},{key:'lastActive',label:'Last active'},{key:'status',label:'Status',render:r=><span className={`status ${r.status==='Active'?'success':r.status==='Suspended'?'danger':'warning'}`}>{r.status}</span>}]} actions={r=><div className="row"><button className="ghost-button" onClick={()=>{updateItem('learners',r.id,{status:r.status==='Active'?'Suspended':'Active'});log('Changed learner status',r.email)}}>{r.status==='Active'?'Suspend':'Activate'}</button><button className="ghost-button" onClick={()=>log('Opened learner support view',r.email)}>Support view</button><button className="ghost-button danger" onClick={()=>{if(confirm('Delete learner demo record?'))removeItem('learners',r.id)}}>Delete</button></div>}/>
  {modal&&<AdminModal title="Create learner" onClose={()=>setModal(false)}><div className="cms-form-grid"><label className="field"><span>Name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Email</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>Company</span><input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label className="field"><span>Plan</span><select value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}><option>Free</option><option>Professional</option><option>Company</option></select></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Invited</option><option>Active</option><option>Suspended</option></select></label></div><button className="button" onClick={create}>Create learner</button></AdminModal>}
 </AdminShell>
}
