'use client';
import {useMemo,useState} from 'react';
const initial=[
 {id:1,course:'Operations Foundations',owner:'Maya Editor',score:94,review:'Approved',freshness:18,accessibility:98,issues:0},
 {id:2,course:'Project Delivery Essentials',owner:'David Chen',score:86,review:'Needs review',freshness:142,accessibility:92,issues:3},
 {id:3,course:'Leadership Essentials',owner:'Elena Markovic',score:91,review:'Approved',freshness:44,accessibility:96,issues:1},
 {id:4,course:'Data & KPI Literacy',owner:'Maya Editor',score:79,review:'Action required',freshness:221,accessibility:88,issues:6}
];
export default function CourseQualityCenter(){const [rows,setRows]=useState(initial);const avg=useMemo(()=>Math.round(rows.reduce((s,x)=>s+x.score,0)/rows.length),[rows]);function run(id){setRows(v=>v.map(x=>x.id===id?{...x,score:Math.min(100,x.score+2),freshness:0,issues:Math.max(0,x.issues-1),review:'Checked today'}:x))}return <div className="stack-gap"><div className="metric-grid four"><div className="metric-card"><span>Quality score</span><b>{avg}/100</b><small>Across published courses</small></div><div className="metric-card"><span>Review due</span><b>{rows.filter(x=>x.freshness>120).length}</b><small>Content freshness</small></div><div className="metric-card"><span>Open issues</span><b>{rows.reduce((s,x)=>s+x.issues,0)}</b><small>Editorial + accessibility</small></div><div className="metric-card"><span>Accessibility</span><b>{Math.round(rows.reduce((s,x)=>s+x.accessibility,0)/rows.length)}%</b><small>Automated checks</small></div></div><div className="dashboard-panel"><div className="row-between"><div><h3>Course quality center</h3><p className="muted">Track freshness, accessibility, review state and publishing quality before content reaches learners.</p></div><button className="button button-small" onClick={()=>rows.forEach(x=>run(x.id))}>Run all checks</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Course</th><th>Quality</th><th>Freshness</th><th>Accessibility</th><th>Issues</th><th>Review</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.course}</b><small>{x.owner}</small></td><td><span className={`skill-score ${x.score>=90?'high':x.score>=80?'mid':'low'}`}>{x.score}</span></td><td>{x.freshness} days</td><td>{x.accessibility}%</td><td>{x.issues}</td><td><span className={`status ${x.review==='Approved'||x.review==='Checked today'?'success':x.review==='Needs review'?'warning':''}`}>{x.review}</span></td><td><button className="ghost-button" onClick={()=>run(x.id)}>Check</button></td></tr>)}</tbody></table></div></div></div>}
