'use client';
import {renderText} from '@/modules/shared/utils/renderText';
import {useEffect,useMemo,useState,use} from 'react';import {courses} from '@/modules/learning/data/catalog';import Link from 'next/link';import {useLearning} from '@/modules/learner/components/LearningStore';import LessonRenderer from '@/modules/learning/components/LessonRenderer';
const legacy={
 'How operating models work':{summary:'Operating models connect teams, ownership, systems, controls and customer outcomes into a repeatable way of running a service.',points:['Start with clear ownership and decision rights.','Processes should show handoffs and escalation paths.','Metrics should support decisions rather than replace judgment.'],scenario:'A recurring service issue affects three teams. What ownership and escalation questions would you clarify first?'},
 'Teams and ownership':{summary:'Cross-functional work is easier when accountability, responsibilities and dependencies are explicit.',points:['Accountability and execution are different concepts.','Dependencies should be visible before they become blockers.','Escalation is a normal part of controlled operations.'],scenario:'Two teams both assume the other owns a customer-impacting issue. What would you document to prevent the same ambiguity next time?'},
 'Product operating model':{summary:'Product teams connect user needs, business priorities, controls and technology constraints into a managed roadmap.',points:['Product ownership is cross-functional by design.','Requirements should include operational dependencies.','Launch readiness is broader than engineering completion.'],scenario:'A feature is technically complete but support and controls are not ready. Is it launch-ready?'}
};
function normalizeCourse(raw){if(!raw)return null;return {...raw,modules:(raw.modules||[]).map((m,i)=>typeof m==='string'?{id:`lesson-${i}`,title:m,type:i===(raw.modules||[]).length-1?'Assessment':'Text lesson',duration:'10 min',required:true,blocks:[]}:m)}}
export default function LearnPage({params}){const {slug}=use(params);const local=useMemo(()=>normalizeCourse(courses.find(c=>c.slug===slug)||courses[0]),[slug]);const [course,setCourse]=useState(local);const {data:learning,setCourseProgress}=useLearning();const [navOpen,setNavOpen]=useState(false);const initialCompleted=learning.completedLessons?.[slug]||0;const [lesson,setLesson]=useState(Math.max(0,Math.min((local?.modules?.length||1)-1,initialCompleted?initialCompleted-1:0)));const [answer,setAnswer]=useState(null);const [checked,setChecked]=useState(false);
 useEffect(()=>{let active=true;fetch(`/api/courses/${encodeURIComponent(slug)}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>{if(active&&j?.course){const next=normalizeCourse(j.course);setCourse(next);setLesson(x=>Math.min(x,Math.max(0,next.modules.length-1)))}}).catch(()=>{});return()=>{active=false}},[slug]);
 if(!course)return null;const current=course.modules[lesson];const title=current?.title||`Lesson ${lesson+1}`;const total=course.modules.length||1;const completed=learning.completedLessons?.[slug]||0;const pct=Math.round(Math.max(completed,lesson)/total*100);const content=legacy[title]||{summary:`This lesson introduces ${title.toLowerCase()} in the context of professional operations.`,points:['Understand why the concept exists and who owns it.','Identify the teams, systems and suppliers involved.','Know what should be documented or escalated.'],scenario:'How would this concept affect another team during a real project or incident?'};const legacyQuiz=lesson===0&&!(current?.blocks||[]).length;const options=['The service owner with clear accountability for the customer outcome','Any external supplier involved','Whichever team notices the issue first'];
 function move(next){const currentCompleted=Math.max(learning.completedLessons?.[slug]||0,Math.min(total,next));setCourseProgress(slug,Math.round(currentCompleted/total*100),currentCompleted);setLesson(next);setAnswer(null);setChecked(false);window.scrollTo({top:0,behavior:'smooth'})}
 function completeCurrent(){const nextCompleted=Math.max(learning.completedLessons?.[slug]||0,lesson+1);setCourseProgress(slug,Math.round(nextCompleted/total*100),nextCompleted);if(lesson<total-1)move(lesson+1)}
 return <section className="section"><div className="container"><div className="dashboard-shell learn-shell"><button className="workspace-mobile-toggle" onClick={()=>setNavOpen(!navOpen)}>Course Outline {navOpen?'↑':'↓'}</button><aside className={`dashboard-nav learn-nav ${navOpen?'mobile-open':''}`}><Link href="/dashboard" className="text-link" style={{margin:'0 10px 18px'}}>← Dashboard</Link><div className="eyebrow" style={{margin:'22px 10px 12px'}}>{course.eyebrow}</div>{course.modules.map((m,i)=><button key={m.id||i} onClick={()=>{move(i);setNavOpen(false)}} className={i===lesson?'active':''}><span>{i<completed?'✓':i+1}</span>{m.title||`Lesson ${i+1}`}</button>)}</aside><div className="dashboard-content lesson-content"><div className="row-between"><div><div className="eyebrow">{course.title}</div><h2>{title}</h2></div><span className="pill">{Math.round((Math.max(completed,lesson+1)/total)*100)}% viewed</span></div><div className="progress" style={{marginBottom:28}}><span style={{width:`${Math.round(completed/total*100)}%`}}/></div>{current.type==='Video'&&<div className="lesson-video"><div className="video-play">▶</div><div><div className="eyebrow">Protected video</div><h3>{title}</h3><p className="muted">Production playback can use signed Mux/Vimeo assets with captions and transcripts.</p></div></div>}<LessonRenderer lesson={current} legacyContent={content}/>{legacyQuiz&&<div className="dashboard-panel"><div className="eyebrow">Knowledge check</div><h3 style={{marginTop:10}}>What best describes good operational ownership?</h3><div className="stack">{options.map((o,i)=><button key={o} onClick={()=>{setAnswer(i);setChecked(false)}} className={answer===i?'option-button selected':'option-button'}><span>{String.fromCharCode(65+i)}</span>{renderText(o)}</button>)}</div><div className="hero-actions"><button className="button" disabled={answer===null} onClick={()=>setChecked(true)}>Check answer</button></div>{checked&&<div className={answer===0?'feedback success':'feedback'}>{answer===0?'Correct. Ownership means clear accountability for the outcome.':'Review the distinction between ownership, contribution and escalation.'}</div>}</div>}<div className="lesson-resource-row"><div><div className="eyebrow">Lesson resources</div><h3>{(current.resources||[]).length?`${current.resources.length} attached resources`:'Notes & framework'}</h3></div><Link className="button button-secondary button-small" href="/resources">Open resources</Link></div><div className="row-between" style={{marginTop:20}}><button className="button button-secondary" disabled={lesson===0} onClick={()=>move(Math.max(0,lesson-1))}>← Previous</button>{lesson===total-1?<Link className="button" href={`/assessment/${course.slug}`}>Start final assessment →</Link>:<button className="button" onClick={completeCurrent}>Complete & continue →</button>}</div></div></div></div></section>}
