import Link from 'next/link';import {CheckoutButton} from '@/modules/billing/components/CheckoutButton';
export const metadata = { title: 'Pricing — OpsAcademy' };
const companyPlans=[
  {name:'Team',price:'€4,900',note:'Up to 25 employees',features:['Core course library','Team dashboard','Assignments','Assessments & certificates','Basic reporting']},
  {name:'Business',price:'€9,900',note:'Up to 75 employees',features:['Everything in Team','Multiple departments','Manager accounts','Custom learning paths','Advanced reporting'],featured:true},
  {name:'Scale',price:'€19,900',note:'Up to 200 employees',features:['Everything in Business','Advanced administration','Onboarding programs','Custom reports','Quarterly training review']},
  {name:'Enterprise',price:'Custom',note:'200+ employees',features:['Custom company academy','Private content programs','Enterprise permissions','Integration roadmap','Dedicated enablement']}
];
export default function PricingPage(){return <><section className="page-hero"><div className="container"><div className="eyebrow">Pricing</div><h1>Start individually. Scale across your team.</h1><p className="lead">Simple professional learning for individuals, with annual company plans and a low-risk 30-day pilot for teams.</p></div></section><section className="section"><div className="container"><div className="section-head"><div className="eyebrow">Individuals</div><h2>One professional membership.</h2></div><div className="grid-2"><div className="card pricing-card"><span className="pill">Free</span><h3 style={{marginTop:20}}>Starter</h3><div className="price">€0</div><p className="muted">Explore the Academy before subscribing.</p><ul className="clean"><li>Selected introductory content</li><li>Knowledge Hub</li><li>Glossary</li><li>Limited resources</li></ul><Link href="/login" className="button button-secondary button-block">Create Free Account</Link></div><div className="card pricing-card featured"><span className="pill">Professional</span><h3 style={{marginTop:20}}>Professional</h3><div className="price">€29 <small>/ month</small></div><p className="muted">Or €249 billed annually.</p><ul className="clean"><li>All Academy courses</li><li>Role-based learning paths</li><li>Assessments</li><li>Verified certificates</li><li>Resource library</li><li>Ask OpsAcademy tutor</li></ul><CheckoutButton planId="professional" label="Start Professional →"/></div></div></div></section><section className="section section-border"><div className="container"><div className="section-head"><div className="eyebrow">Companies</div><h2>Annual plans for teams.</h2><p className="lead">Start with the 30-day pilot, then move to the plan that matches your employee count and administration needs.</p></div><div className="grid-4">{companyPlans.map(plan=><div className={`card pricing-card ${plan.featured?'featured':''}`} key={plan.name}><span className="pill">{plan.name}</span><h3 style={{marginTop:20}}>{plan.name}</h3><div className="price company-price">{plan.price}{plan.price!=='Custom'&&<small> / year</small>}</div><p className="muted">{plan.note}</p><ul className="clean">{plan.features.map(f=><li key={f}>{f}</li>)}</ul><Link href="/for-companies" className={`button button-block ${plan.featured?'':'button-secondary'}`}>{plan.name==='Enterprise'?'Talk to Sales':'Request Demo'}</Link></div>)}</div><div className="pilot-strip"><div><span className="pill">30-day pilot</span><h3>Validate the program with up to 10 employees.</h3><p className="muted">operations Fundamentals + one learning path + assessments + certificates + manager dashboard + final learning report.</p></div><div><div className="price">€1,500</div><Link className="button" href="/for-companies#pilot">Start pilot →</Link></div></div></div></section></>}
