'use client';
import {renderText} from '@/modules/shared/utils/renderText';
import {useState} from 'react';
const standards=[
 {key:'scorm12',name:'SCORM 1.2',desc:'Export course packages for established LMS environments.',state:'Ready'},
 {key:'scorm2004',name:'SCORM 2004',desc:'Structured completion and score interoperability.',state:'Beta'},
 {key:'xapi',name:'xAPI',desc:'Emit learning statements to external Learning Record Stores.',state:'Beta'},
 {key:'lti',name:'LTI 1.3',desc:'Launch OpsAcademy learning from compatible learning platforms.',state:'Planned'}
];
export default function InteroperabilityManager(){const [enabled,setEnabled]=useState({scorm12:true,scorm2004:true,xapi:false,lti:false});const [endpoint,setEndpoint]=useState('https://lrs.example.com/xapi');const [message,setMessage]=useState('');function exportPkg(type){setMessage(`${type} export queued for Operations Foundations. Demo package metadata created.`);setTimeout(()=>setMessage(''),2500)}return <div className="stack-gap"><div className="dashboard-panel"><h3>LMS interoperability</h3><p className="muted">Prepare content for external LMS delivery and synchronize completion events without duplicating course authoring.</p>{message&&<div className="runtime-callout"><b>{message}</b></div>}<div className="integration-standard-grid">{standards.map(s=><article className="admin-edit-card" key={s.key}><div className="row-between"><b>{s.name}</b><span className={`status ${s.state==='Ready'?'success':s.state==='Beta'?'warning':''}`}>{s.state}</span></div><p className="muted small">{s.desc}</p><label className="check-row"><input type="checkbox" checked={!!enabled[s.key]} onChange={e=>setEnabled(v=>({...v,[s.key]:e.target.checked}))}/> Enabled for enterprise plans</label>{s.key.startsWith('scorm')&&<button className="button button-secondary button-small" onClick={()=>exportPkg(s.name)}>Export test package</button>}</article>)}</div></div><div className="grid-2"><div className="dashboard-panel"><h3>xAPI / LRS configuration</h3><label className="field"><span>LRS endpoint</span><input value={endpoint} onChange={e=>setEndpoint(e.target.value)}/></label><label className="field"><span>Client key</span><input value="••••••••••••" readOnly/></label><div className="row"><button className="button button-small">Test connection</button><button className="button button-secondary button-small">Rotate secret</button></div></div><div className="dashboard-panel"><h3>Package history</h3>{[['Operations Foundations','SCORM 1.2','Ready'],['Manager Essentials','SCORM 2004','Ready'],['Company Academy / Safety','xAPI','Synced']].map(r=><div className="admin-pipeline-row" key={r[0]}><span><b>{renderText(r[0])}</b><small>{renderText(r[1])}</small></span><span className="status success">{renderText(r[2])}</span></div>)}</div></div></div>}
